spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_USERCENTER_URL:jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERCENTER_USERNAME:root}
    password: ${DB_USERCENTER_PWD:123456}


codex:
  jdbc:
    url: jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  package:
    entity-path: pub.codex.user.entity
    mapper-path: pub.codex.user.db.mapper
    mapperXML-path: mapper
    service-path: pub.codex.user.db.service
    serviceImpl-path: pub.codex.user.db.service.impl
    controller-path: pub.codex.user.controller
  prefix: t_,tb_,test_
apix:
  controllerPackage: pub.codex.user.controller

logging:
  level:
    root: info
    com.jnh: debug


