server:
  port: 6100

spring:
  application:
    name: 'codex-server-user-center'
  profiles:
    active: local

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_USERCENTER_URL:jdbc:mysql://localhost:3306/user_center?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false}
    username: ${DB_USERCENTER_USERNAME}
    password: ${DB_USERCENTER_PWD}

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: pub.codex.user.db.entity
  global-config:
    #逻辑删除配置
    db-config:
      logic-delete-field: deleted
      # 设置逻辑删除值为当前时间
      logic-delete-value: "now()"
      # 设置未删除值为 "null"
      logic-not-delete-value: "null"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
