server:
  port: 8200

spring:
  application:
    name: 'codex-server-user-center'
  profiles:
    active: local

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: pub.codex.user.entity
  global-config:
    #逻辑删除配置
    db-config:
      logic-delete-field: deleted
      # 设置逻辑删除值为当前时间
      logic-delete-value: "now()"
      # 设置未删除值为 "null"
      logic-not-delete-value: "null"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
