codex:
  jdbc:
    url: jdbc:mysql://localhost:3306/user_center?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  package:
    entity-path: pub.codex.entity.usercenter.entity
    mapper-path: pub.codex.db.usercenter.mapper
    mapperXML-path: mapper
    service-path: pub.codex.db.usercenter.service
    serviceImpl-path: pub.codex.db.usercenter.service.impl
    controller-path: pub.codex.usercenter.controller
  prefix: t_,tb_,test_
apix:
  controllerPackage: pub.codex.usercenter.controller