server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: 'codex-server-oauth-center'
  profiles:
    active: local

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_USERCENTER_URL:jdbc:mysql://localhost:3306/codex?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERCENTER_USERNAME:root}
    password: ${DB_USERCENTER_PWD:123456}

#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: pub.codex.oauth.db.entity
  global-config:
    #逻辑删除配置
    db-config:
      logic-delete-field: deleted
      # 设置逻辑删除值为当前时间
      logic-delete-value: "now()"
      # 设置未删除值为 "null"
      logic-not-delete-value: "null"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true

